name: dual_screen
description: Dual-screen and foldable support, like hinge angle sensor data.
version: 1.0.0+3
homepage: https://docs.microsoft.com/en-us/dual-screen/
repository: https://github.com/microsoft/flutter-dualscreen

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.microsoft.flutterdualscreen
        pluginClass: DualScreenInfo